Krajské volby 2012
========================================================

```{r tidy=FALSE}
kraje <- read.csv("~/github/local/ElectionsCZ/CSVKraje/Kraje_CandRegDetails2012_2.csv")
library(ggplot2)
library(stringr)
library(plyr)
library(reshape)

# load data for resolving female names
firstnames_female <- read.csv("~/github/local/ElectionsCZ/OtherData/NamesFemale.csv")
firstnames_female$female <- 1
firstnames_male <- read.csv("~/github/local/ElectionsCZ/OtherData/NamesMale.csv")
firstnames_male$female <- 0

nameslist <- rbind(firstnames_male, firstnames_female)
nameslist <- rename(nameslist, c("Name" = "KandKrestniJmeno"))
nameslist$Rank <- NULL
nameslist$Count <- NULL

merge(kraje, nameslist)

ciselnik_kandidatky <- read.csv("~/github/local/ElectionsCZ/OtherData/Ciselnik_KZ_2012_kandidatky.csv")
ciselnik_kandidatky <- rename(ciselnik_kandidatky, c("KandNum" = "Kandidatka"))
kraje <- merge(ciselnik_kandidatky, kraje, by = "Kandidatka")

ciselnik_kraje <- read.csv("~/github/local/ElectionsCZ/OtherData/Ciselnik_KZ_2012_kraje.csv")
kraje <- merge(ciselnik_kraje, kraje, by = "Kraj")

kraje_pocetkand <- ddply(kraje, .(Kraj, Kandidatka), nrow)
kraje_pocetkand <- rename(kraje_pocetkand, c("V1"="PocetKand"))
kraje <- merge(kraje, kraje_pocetkand, by=c("Kandidatka","Kraj"))


avgfemale <- ddply(kraje, .(Kraj, Kandidatka), summarise,
                   FemPerc = mean(female))

kraje_fem <- subset(kraje, female == 1)
avgpostfemale <- ddply(kraje_fem, .(Kraj, Kandidatka), summarise,
                      FemPos = 1-mean(PoradiKand/PocetKand))

women <- merge(avgfemale, avgpostfemale, c("Kandidatka", "Kraj"))
women <- merge(women, ciselnik_kandidatky)
women <- merge(women, ciselnik_kraje)

rm(kraje_pocetkand, ciselnik_kraje, ciselnik_kandidatky, kraje_fem,
   avgfemale, avgpostfemale)

plot_women <- ggplot(subset(women, str_detect(women$KandName,"KDU")),
               aes(FemPerc, FemPos,
                  colour = as.factor(KandName),
                  label=KrajName)) +
          geom_text() +
          #facet_wrap(~KandName) + 
          scale_color_discrete("clarity") +
          ylim(0,1) + 
          xlim(0,1)

```

You can also embed plots, for example:

```{r fig.width=7, fig.height=6}
plot(plot_women)
```
